const menu = [
    {  nombre: 'Ao Haru Ride', image: "https://i.postimg.cc/9rwY9jTP/Ao-Haru-Ride.jpg" },
    {  nombre: 'Clannad y Clannad', image: "https://i.postimg.cc/ftbxR4D9/Clannad-y-Clannad.jpg" },
    {  nombre: 'Fruits Basket', image: "https://i.postimg.cc/Y4M6TGP8/Fruits-Basket.jpg" },
    {  nombre: 'Given', image: "https://i.postimg.cc/w1KccbcC/Given.jpg" },
    {  nombre: 'Golden Time', image: "https://i.postimg.cc/0zpGtdVb/Golden-Time.jpg" },
    {  nombre: 'Just Because', image: "https://i.postimg.cc/vgS51PZS/Just-Because.jpg" },
    {  nombre: 'Kimi ni Todoke', image: "https://i.postimg.cc/LqDtS4KS/Kimi-ni-Todoke.jpg" },
    {  nombre: 'Kokoro Connect', image: "https://i.postimg.cc/BPLH2x8Z/Kokoro-Connect.jpg" },
    {  nombre: 'Lovely Complex', image: "https://i.postimg.cc/qgzsfdmf/Lovely-Complex.jpg" },
    {  nombre: 'My Little Monster', image: "https://i.postimg.cc/dLCG1jP4/My-Little-Monster-Tonari-no-Kaibutsu-kun.jpg" },
    {  nombre: 'My Youth Romantic Comedy', image: "https://i.postimg.cc/jCmztk9D/My-Youth-Romantic-Comedy-Is-Wrong-As-I-Expected-Yahari-Ore-no-Seishun-Love-Comedy-wa-Machigatteiru.jpg" },
    {  nombre: 'Nisekoi', image: "https://i.postimg.cc/yDzcS37B/Nisekoi.jpg" },
    {  nombre: 'Ore Monogatari', image: "https://i.postimg.cc/5Xqv59tz/Ore-Monogatari.jpg" },
    {   nombre: 'ReLIFE', image: "https://i.postimg.cc/YGVm2hd5/ReLIFE.jpg" },
    {  nombre: 'Say I Love You', image: "https://i.postimg.cc/NydHVNmf/Say-I-Love-You-Sukitte-Ii-na-yo.jpg" },
    {  nombre: 'Sword Art Online', image: "https://i.postimg.cc/62TvNdfV/Sword-Art-Online-Particularly.jpg" },
    {  nombre: 'Tada Never Falls in Love', image: "https://i.postimg.cc/21wbbHHF/Tada-Never-Falls-in-Love.jpg" },
    {  nombre: 'Anohana', image: "https://i.postimg.cc/zHgHy8MV/The-Flower-We-Saw-That-Day.jpg" },
    {  nombre: 'The Pet Girl of Sakurasou', image: "https://i.postimg.cc/6T2vjf3t/The-Pet-Girl-of-Sakurasou-Sakurasou-no-Pet-na-Kanojo.jpg" },
    {  nombre: 'Toradora', image: "https://i.postimg.cc/5H2HwwTc/Toradora-Poster.jpg" },
    {  nombre: 'Tsuki ga Kirei', image: "https://i.postimg.cc/Z0Gy1vB3/Tsuki-ga-Kirei.jpg" },
    {  nombre: 'Violet Evergarden', image: "https://i.postimg.cc/nCqQZVBW/Violet-Evergarden.jpg" },
    {  nombre: 'Your Lie in April', image: "https://i.postimg.cc/RW9J0rTZ/Your-Lie-in-April-Shigatsu-wa-Kimi-no-Uso.jpg" },
    {  nombre: 'Rascal Does Not Dream of Bunny Girl Senpai', image: "https://i.postimg.cc/gwzhg9wT/Rascal-Does-Not-Dream-of-Bunny-Girl-Senpai-Seishun-Buta-Yarou-wa-Bunny-Girl-Senpai-no-Yume-wo-Minai.jpg" }
];
